"""iCalendar (RFC 5545) agenda feeds.

Distinct from `site/src/feed.njk`'s RSS syndication feed: that one is a
reading list for a feed reader, this one is a subscribable calendar for a
calendar client. The request it answers: a shared
calendar with nothing to administer and no account -- a static file, not a
service.

Two feeds, two audiences:

* The **public** feed is built entirely on the JavaScript side
  (`site/.eleventy.js::agendaCalendar`, `site/src/agenda.njk`), published as
  part of the showcase at `/agenda.ics` -- scheduled editions only, title,
  start, end, timezone and the event page's address, and nothing else.
  Nothing here builds it; it has no Python half.
* The **internal** feed is this module's own: everything the public one
  carries, plus the preparation deadlines the board is already tracking
  (`notify.due_date`) -- so a volunteer subscribed to it sees "Board decision
  due" and "Recording due" lines alongside the scheduled talks, not a second,
  separate list to check. It is generated by `convener-agenda-internal`
  (`cli.py::agenda_internal`) into `instance/public-data/agenda-internal.ics`, and
  `.gitignore` carries a deliberate, named exception for that one path (the
  same shape `!instance/public-data/survey-status.json` already has) so
  `.github/workflows/deploy.yml`'s own "Commit internal agenda" step can
  commit it back to this repository -- never to the published one. Nothing in
  this repository's build ever copies `instance/public-data/agenda-internal.ics` into
  `app/public/` or `site/src/_data/` (unlike `certificates-public.json` and
  `survey-status.json`, which each have exactly that copy step,
  `app/scripts/copy-certificates.mjs` and `copy-survey-status.mjs`): that
  absence is what keeps this feed out of both published bundles, by
  construction rather than by a flag someone could leave off. See
  `tools/tests/test_agenda.py::
  test_nothing_in_the_build_ever_copies_the_internal_agenda_into_a_published_bundle`.

Preparation deadlines are not re-derived here. `notify.due_date` already
computes, per speaker record, the one step it is currently waiting on and
the day it is due -- the exact "preparation deadline" this feed needs, built
for the daily digest and already tested there. Writing a second copy of that
rule would be exactly the cross-language divergence this project has already
been bitten by more than once, one language over.

The Europe/Paris standing-start rule (`visual.paris_standing_start`,
`site/.eleventy.js::parisStandingStart`, D-14, `tools/tests/fixtures/
paris-standing-start.json`) is reused too, but at one remove: this module
does not call `paris_standing_start` itself (that function returns a
human-readable offset/label pair, "+02:00"/"CEST", built for a printed date
line). It instead builds the aware `datetime` directly from `governance.PARIS`
-- the same `zoneinfo.ZoneInfo("Europe/Paris")` object `paris_standing_start`
itself reads -- and asks it for its own UTC instant. That is not a fourth
implementation of the DST rule: there is no separate resolution of "which
offset applies" to get right or to get wrong differently: `datetime.astimezone`
consults the identical IANA data the fixture's own eight cases already pin
`paris_standing_start` against, so the two cannot disagree.

RFC 5545 TEXT escaping and 75-octet line folding are, by contrast,
deliberately *not* bound to a shared fixture the way the timezone rule is:
they are mechanical, RFC-mandated transformations with no project decision
in them for the two languages to disagree about, unlike "12:30 Europe/Paris,
CET or CEST". `tools/tests/test_agenda.py` and `tools/tests/test_site.py`
each check their own side directly against the RFC -- parsing the rendered
file back with an independent reader, never re-running this module's own
escape/fold functions -- rather than cross-checking the two implementations
against each other, which could let a shared misreading of the RFC through
unnoticed.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from datetime import UTC, date, datetime, timedelta
from typing import Any, Final

from .declaration import published
from .governance import PARIS
from .notify import Deadline, due_date
from .registration import signup_url
from .visual import STANDING_START_LOCAL

#: `instance/data/config.yml::seminar_duration_minutes`'s own fallback --
#: `sweep.sweep`'s identical `int(config.get("seminar_duration_minutes") or
#: 90)` is this key and this default's first use in this codebase; this is
#: its second, read the same way for the same reason: an unattended job must
#: still produce a plausible calendar entry from a config missing the key,
#: or one a human mistyped, never fail outright.
_DEFAULT_DURATION_MINUTES: Final = 90

#: Who runs this series -- read once, used for the calendar name a
#: subscriber sees and for the `PRODID` every emitted calendar carries.
_IDENTITY: Final = published.load_identity()

#: The one-line calendar name a subscribing client shows (`X-WR-CALNAME`, a
#: de facto standard every major client reads, though it is not part of
#: RFC 5545 itself). The organisation is the instance's, read from
#: `instance/config.json` like the UID domain below -- a subscriber sees
#: this string in their own calendar list, so a duplicate whose internal
#: agenda announced somebody else would be an odd thing to explain.
_CALENDAR_NAME: Final = f"{_IDENTITY.organisation} internal agenda"

#: The right-hand side of every `UID` this module mints. RFC 5545 §3.8.4.7
#: asks for a globally unique identifier and recommends the address-like
#: form used below, whose domain part must be one the producer controls --
#: so it is this instance's own published host, read from
#: `instance/config.json` like every other published address in this
#: repository, and not a value a duplicate would have to remember to
#: change. Nothing ever resolves it: it is a name, not an address.
_UID_DOMAIN: Final = published.load().host

#: RFC 5545 §3.1: a content line SHOULD be folded at this many octets.
_FOLD_LIMIT: Final = 75

#: A continuation line's own content budget: one of the 75 octets is the
#: mandatory single leading space RFC 5545 §3.1 inserts after each fold.
_CONTINUATION_LIMIT: Final = 74


def _seminar_duration_minutes(config: Any) -> int:
    """`config["seminar_duration_minutes"]`, or the project's own 90-minute
    default when the config does not say one, cannot be parsed as a plain
    positive integer, or is not a mapping at all -- an unattended job reads
    an absent or malformed value as "assume the ordinary length", never as a
    reason to stop.
    """
    if isinstance(config, Mapping):
        raw = config.get("seminar_duration_minutes")
        if isinstance(raw, int) and not isinstance(raw, bool) and raw > 0:
            return raw
    return _DEFAULT_DURATION_MINUTES


def _escape_text(value: str) -> str:
    """RFC 5545 §3.3.11 TEXT escaping: a backslash, then a semicolon, then a
    comma, then a literal line break -- in that order, so escaping a later
    character never re-escapes a backslash this function just inserted for
    an earlier one. See the module docstring for why this is not bound to
    `site/.eleventy.js::icsEscapeText` by a shared fixture.
    """
    escaped = value.replace("\\", "\\\\").replace(";", "\\;").replace(",", "\\,")
    return escaped.replace("\r\n", "\\n").replace("\r", "\\n").replace("\n", "\\n")


def _fold_line(line: str) -> str:
    """Fold one already-escaped "NAME:value" content line at 75 octets (RFC
    5545 §3.1), splitting only on a UTF-8 character boundary -- never inside
    a multi-byte sequence's own continuation bytes (`10xxxxxx`), which would
    corrupt the file from that point on rather than merely misplace one line
    break. Twin of `site/.eleventy.js::icsFoldLine`.
    """
    data = line.encode("utf-8")
    if len(data) <= _FOLD_LIMIT:
        return line
    parts: list[str] = []
    start = 0
    budget = _FOLD_LIMIT
    while start < len(data):
        end = min(start + budget, len(data))
        while end < len(data) and (data[end] & 0xC0) == 0x80:
            end -= 1
        parts.append(data[start:end].decode("utf-8"))
        start = end
        budget = _CONTINUATION_LIMIT
    return "\r\n ".join(parts)


def _fold_all(lines: Sequence[str]) -> str:
    return "\r\n".join(_fold_line(line) for line in lines)


def _utc_stamp(instant: datetime) -> str:
    """`instant` (any aware `datetime`) as an RFC 5545 UTC DATE-TIME, e.g.
    `20260910T103000Z`."""
    return instant.astimezone(UTC).strftime("%Y%m%dT%H%M%SZ")


def _edition_start(talk_date: date) -> datetime:
    """The real Europe/Paris instant this project's standing 12:30 start
    resolves to on `talk_date`, DST included. See the module docstring for
    why this reads `governance.PARIS` directly rather than calling
    `visual.paris_standing_start`.
    """
    return datetime.combine(talk_date, STANDING_START_LOCAL, tzinfo=PARIS)


def _edition_vevent(event: Mapping[str, Any], *, duration_minutes: int) -> str:
    """One VEVENT for a `scheduled` edition: title, start, end and the event
    page's address -- never the meeting room (D-19). `UID` is that same
    address, the identical identity `site/.eleventy.js::agendaVevent` and
    `site/src/feed.njk`'s own `<guid isPermaLink="true">` already use for
    it, so all three name the same edition the same way. `DTSTAMP` is the
    same instant as `DTSTART`, not the real clock: a feed regenerated on
    every push must not change for a reason that has nothing to do with its
    own content -- the exact discipline `paris_today` exists to enforce
    project-wide, extended here to a property RFC 5545 requires but does not
    otherwise constrain the meaning of.
    """
    # `edition_code` (D-19), never `id`: a speaker record's `id`
    # ("spk-014") is its own internal record key, `notify.py`'s own "name
    # the record, never the person" identity for a deadline entry below --
    # the *edition's* own public identifier, the one `signup_url` and the
    # event page's own permalink both expect, is `edition_code`
    # ("MRG-05"). `KeyError`/`ValueError` below (an absent, non-string or
    # blank code) makes this edition unrepresentable rather than published
    # at the wrong address.
    edition_code = str(event["edition_code"])
    if not edition_code:
        raise ValueError("edition_code is blank")
    url = signup_url(edition_code.lower())
    start = _edition_start(date.fromisoformat(str(event["date"])))
    dtstart = _utc_stamp(start)
    dtend = _utc_stamp(start + timedelta(minutes=duration_minutes))
    return _fold_all(
        [
            "BEGIN:VEVENT",
            f"UID:{url}",
            f"DTSTAMP:{dtstart}",
            f"DTSTART:{dtstart}",
            f"DTEND:{dtend}",
            f"SUMMARY:{_escape_text(str(event['title']))}",
            f"LOCATION:{_escape_text(url)}",
            f"URL:{url}",
            "END:VEVENT",
        ]
    )


#: A UID suffix from a step label ("Board decision" -> "board-decision"):
#: opaque text is all RFC 5545 requires of a UID, but a readable one is
#: easier to recognise across regenerations when the same record's step
#: changes -- lower-cased, non-alphanumeric runs collapsed to one hyphen,
#: never empty for any of `STEP_LABELS`' own four values.
_SLUG_RE: Final = re.compile(r"[^a-z0-9]+")


def _slug(label: str) -> str:
    return _SLUG_RE.sub("-", label.lower()).strip("-")


def _deadline_vevent(deadline: Deadline, speaker_id: str) -> str:
    """One all-day VEVENT for a preparation deadline this project is already
    tracking (`notify.due_date`) -- never a VTODO: a subscription some
    calendar clients treat as read-only ignores a VTODO's own DUE property
    entirely, which would make this half of the internal feed invisible on
    exactly the clients this feature exists to reach.

    All-day (`VALUE=DATE`, no time-of-day, no `DTEND`): `deadline.due` is a
    calendar day with no wall-clock instant of its own -- `notify.py`'s own
    docstring is explicit that these are calendar days, not Paris local
    times -- so there is no timezone to resolve here at all, only a date to
    place the entry on. RFC 5545 gives a `DATE`-valued `DTSTART` with no
    `DTEND` a duration of exactly one day, which is what this deadline is.

    `deadline.step` and `speaker_id` only: never a speaker's name, e-mail or
    affiliation -- the same discipline `notify.py`'s own module docstring
    states at length for the digest this exact `Deadline` already feeds, and
    the project-wide rule that no personal data beyond what is already
    public may reach a generated artefact.
    """
    due_compact = deadline.due.replace("-", "")
    dtstamp = f"{due_compact}T000000Z"
    uid = f"{speaker_id}-{_slug(deadline.step)}@{_UID_DOMAIN}"
    summary = _escape_text(f"{deadline.step} due \u2014 {speaker_id}")
    return _fold_all(
        [
            "BEGIN:VEVENT",
            f"UID:{uid}",
            f"DTSTAMP:{dtstamp}",
            f"DTSTART;VALUE=DATE:{due_compact}",
            f"SUMMARY:{summary}",
            "END:VEVENT",
        ]
    )


def build_internal_calendar(speakers: Sequence[Any], config: Any) -> str:
    """The internal agenda feed in full: every `scheduled` edition (the
    same filter the public feed applies), plus one all-day entry per
    speaker record currently waiting on a preparation deadline
    (`notify.due_date`) -- soonest first, in both halves, so a subscriber's
    calendar shows what is coming up next before what is further out.

    `speakers` need not be well-formed: a non-mapping entry, a missing
    `id`, or a date `date.fromisoformat` refuses are all skipped rather
    than raised on, the same "an unattended job degrades to fewer lines,
    never a guessed one" discipline `notify.py` already documents for the
    identical input.
    """
    duration = _seminar_duration_minutes(config)
    editions: list[tuple[str, str]] = []
    for entry in speakers:
        if not isinstance(entry, Mapping) or entry.get("status") != "scheduled":
            continue
        try:
            editions.append(
                (str(entry["date"]), _edition_vevent(entry, duration_minutes=duration))
            )
        except (KeyError, ValueError):
            continue
    editions.sort(key=lambda pair: pair[0])

    deadlines: list[tuple[str, str]] = []
    for entry in speakers:
        if not isinstance(entry, Mapping):
            continue
        speaker_id = entry.get("id")
        if not isinstance(speaker_id, str) or not speaker_id:
            continue
        deadline = due_date(entry, config)
        if deadline is None:
            continue
        deadlines.append((deadline.due, _deadline_vevent(deadline, speaker_id)))
    deadlines.sort(key=lambda pair: pair[0])

    header = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        f"PRODID:-//{_IDENTITY.organisation}//{_IDENTITY.series} (internal)//EN",
        "CALSCALE:GREGORIAN",
        f"X-WR-CALNAME:{_escape_text(_CALENDAR_NAME)}",
    ]
    footer = ["END:VCALENDAR"]
    body = [
        *header,
        *(vevent for _, vevent in editions),
        *(vevent for _, vevent in deadlines),
        *footer,
    ]
    return "\r\n".join(body) + "\r\n"
