"""The decision register, derived from the commit history.

The board keeps no database, so the git history is the audit trail. This
module turns that history into the one table a volunteer can read: which
record was acted on, when, by whom. Nothing here is written by hand and
nothing here can be: the input is `git log`, and the output is a pure
function of it.

Derived, never authored
-----------------------
Three properties, together, are what make that structural rather than a
convention somebody is asked to respect.

* **No free-text cell exists.** Every cell is a calendar day, an identifier
  matching `commit_format._TOKEN`, or a phrase drawn verbatim from `ACTS` and
  `QUALIFIERS`. There is no column a remark about a volunteer could occupy --
  the same absence that `commit_format` establishes for the message itself,
  carried through to the rendering. A cell therefore cannot contain a `|`
  either, so no row can be made to break the table it sits in.
* **Regeneration is total, not incremental.** `render_register` is given the
  whole history and returns the whole file; the job replaces the file rather
  than appending to it. An edit made by hand does not merely violate a rule,
  it disappears on the next push -- there is no state anywhere that could
  preserve it. `convener-register --check` runs that same derivation as an
  assertion, so CI refuses the edit at the push that carries it instead of
  leaving it standing in the repository until the next run undoes it.
* **The rendering is a function of the commits alone.** No clock, no
  `instance/data/*.yml`, no generation counter, no environment. Two runs over the same
  commits produce byte-identical files, which is what lets the job commit
  "only if it changed" and mean it.

Append-only
-----------
Entries sort by day with a stable sort, and ties keep history order. A new
commit therefore adds a row and never rewrites one: a reader who quoted a line
last month can still find that exact line today.

Silence is not evidence
-----------------------
The grammar of decision commits is younger than the board. Decisions taken
before it are not in this table and have deliberately not been reconstituted
-- inventing rows for them would be the opposite of an audit trail. The
rendered file says so in its own words, so an empty table reads as "nothing
has been recorded through the app yet" and never as "the board has decided
nothing".

A scheduled job cannot appear in this register at all. The actor column is
read out of the message, where the grammar requires `by <login>`; the commit's
own author is never consulted. A job has no `by`, so it writes no row -- and
the register's own regeneration commits, being `docs:` commits, are ordinary
ones that this module ignores like any other.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date, datetime
from typing import Final

from convener_ops.commit_format import ACTS, Decision, parse_decision
from convener_ops.governance import paris_today

#: The `git log --format=` string this module's parser expects: the author
#: instant, a unit separator, the subject. The separator is a character no
#: subject can contain, so no subject can forge a field boundary.
LOG_FORMAT: Final = "%aI\x1f%s"

_SEPARATOR: Final = "\x1f"

_PREAMBLE: Final = """# Decision register

Derived from the commit history by `convener-register`. Do not edit this file: it is
regenerated in full from the commits on every push, so a change made here is
overwritten rather than kept.

Every cell below is a calendar day, an identifier, or a phrase from the closed
vocabulary in `tools/convener_ops/commit_format.py`. The table has no free-text
column, so it records what happened to a record and never passes judgement on
the volunteer who acted. Reasons a volunteer chose to state live with the
record itself, in `instance/data/speakers.yml`, where they can still be corrected; a
line of this register, once written, never changes.

This register begins with the grammar of decision commits, which is younger
than the board. Decisions taken before it are not listed here and have not been
reconstituted from memory -- an audit trail that invented its own past would be
worth nothing. Those earlier decisions are recorded elsewhere and are not lost:
the ballots the board cast on the speakers migrated with them into
`instance/data/speakers.yml`, and the reasoning behind the board's standing choices is
in `decisions.md`, next to this file. A short or empty table therefore dates
the arrival of the tooling, not the activity of the board.
"""

_COLUMNS: Final = "| Date | Act | Record | Recorded by |"
_RULE: Final = "|---|---|---|---|"
_EMPTY: Final = "No decision has been recorded through the app yet."


@dataclass(frozen=True)
class RegisterEntry:
    """One decision, and the Paris day its commit was authored on."""

    day: date
    decision: Decision


def _entry(line: str) -> RegisterEntry | None:
    """One log line as an entry, or `None` if it records no decision.

    Returning `None` for anything unreadable is the whole point: an ordinary
    commit, a malformed one and a line git never produced all take the same
    silent exit, so the register can be derived from an unfiltered log.
    """
    instant, _, subject = line.partition(_SEPARATOR)
    if not subject:
        return None
    decision = parse_decision(subject)
    if decision is None:
        return None
    try:
        authored = datetime.fromisoformat(instant)
    except ValueError:
        return None
    # The commit's own offset is whatever laptop wrote it; the register's days
    # are Paris days like every other date in this repository.
    return RegisterEntry(paris_today(authored), decision)


def entries_from_log(text: str) -> list[RegisterEntry]:
    """Every decision in a `git log --reverse --format=LOG_FORMAT` stream.

    Order is preserved, so the caller's history order survives into the stable
    sort that `render_register` applies.
    """
    return [entry for line in text.splitlines() if (entry := _entry(line)) is not None]


def _row(entry: RegisterEntry) -> str:
    decision = entry.decision
    act = ACTS[decision.kind]
    if decision.detail:
        act = f"{act} ({decision.detail})"
    return f"| {entry.day.isoformat()} | {act} | {decision.entity} | {decision.actor} |"


def render_register(decisions: Sequence[RegisterEntry]) -> str:
    """The whole register file, for exactly these decisions.

    Pure, and pure on purpose: the same input always renders the same bytes,
    which is what makes "commit only if it changed" a true statement about the
    history rather than about the moment the job happened to run.
    """
    lines = [_PREAMBLE]
    if not decisions:
        lines.append(_EMPTY + "\n")
    else:
        rows = [_row(entry) for entry in sorted(decisions, key=lambda e: e.day)]
        lines.append("\n".join([_COLUMNS, _RULE, *rows]) + "\n")
    return "\n".join(lines)
