// Generated by scripts/generate_brand_css.py from data/brand.json.
// Do not edit by hand: run `uv run python ../scripts/generate_brand_css.py` from `tools/` and commit what it
// writes.
export const colors = {
  paper: '#ffffff', surface: '#ffffff',
  ink: '#522f3c', inkMuted: '#794658',
  primary: '#fecac1', primaryHover: '#a24535',
  accent: '#012765', border: '#d0bbc3',
  danger: '#9b2226', info: '#4a6c75',
} as const;

export const fonts = {
  display: '"Archivo", system-ui, sans-serif',
  body: '"Archivo", system-ui, sans-serif',
  mono: '"JetBrains Mono", monospace',
} as const;
